
package mx.gob.segob.nsjp.ws.cliente.avisodetencion;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;

import javax.xml.namespace.QName;

/**
 * This class was generated by Apache CXF 2.4.2
 * 2012-01-16T19:57:36.100-06:00
 * Generated source version: 2.4.2
 * 
 */
public final class RegistrarAvisoSinDetencionDeAreaExternaExporter_RegistrarAvisoSinDetencionDeAreaExternaExporterImplPort_Client {

    private static final QName SERVICE_NAME = new QName("http://impl.ws.service.nsjp.segob.gob.mx/", "RegistrarAvisoSinDetencionDeAreaExternaExporterImplService");

    private RegistrarAvisoSinDetencionDeAreaExternaExporter_RegistrarAvisoSinDetencionDeAreaExternaExporterImplPort_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = RegistrarAvisoSinDetencionDeAreaExternaExporterImplService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        RegistrarAvisoSinDetencionDeAreaExternaExporterImplService ss = new RegistrarAvisoSinDetencionDeAreaExternaExporterImplService(wsdlURL, SERVICE_NAME);
        RegistrarAvisoSinDetencionDeAreaExternaExporter port = ss.getRegistrarAvisoSinDetencionDeAreaExternaExporterImplPort();  
        
        {
        System.out.println("Invoking registrarAvisoSinDetencion...");
        mx.gob.segob.nsjp.ws.cliente.avisodetencion.AvisoDesignacionWSDTO _registrarAvisoDesignacion_arg0 = null;
        java.lang.Long _registrarAvisoDesignacion_arg1 = null;
        java.lang.String _registrarAvisoDesignacion_arg2 = "";
        java.lang.Long _registrarAvisoDesignacion_arg3 = null;
        try {
            mx.gob.segob.nsjp.ws.cliente.avisodetencion.AvisoDesignacionWSDTO _registrarAvisoDeignacion__return = port.registrarAvisoSinDetencion(_registrarAvisoDesignacion_arg0, _registrarAvisoDesignacion_arg1, _registrarAvisoDesignacion_arg2, _registrarAvisoDesignacion_arg3);
            System.out.println("registrarAvisoSinDetencion.result=" + _registrarAvisoDeignacion__return);

        } catch (NSJPNegocioException_Exception e) { 
            System.out.println("Expected exception: NSJPNegocioException has occurred.");
            System.out.println(e.toString());
        }
            }

        System.exit(0);
    }

}
