package mx.gob.segob.nsjp.ws.cliente.avisodetencion;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.FaultAction;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.4.2
 * 2012-01-16T19:57:36.162-06:00
 * Generated source version: 2.4.2
 * 
 */
@WebService(targetNamespace = "http://ws.service.nsjp.segob.gob.mx/", name = "RegistrarAvisoSinDetencionDeAreaExternaExporter")
@XmlSeeAlso({ObjectFactory.class})
public interface RegistrarAvisoSinDetencionDeAreaExternaExporter {

    @WebResult(name = "return", targetNamespace = "")
    @Action(input = "http://ws.service.nsjp.segob.gob.mx/RegistrarAvisoSinDetencionDeAreaExternaExporter/registrarAvisoSinDetencionRequest", output = "http://ws.service.nsjp.segob.gob.mx/RegistrarAvisoSinDetencionDeAreaExternaExporter/registrarAvisoSinDetencionResponse", fault = {@FaultAction(className = NSJPNegocioException_Exception.class, value = "http://ws.service.nsjp.segob.gob.mx/RegistrarAvisoSinDetencionDeAreaExternaExporter/registrarAvisoSinDetencion/Fault/NSJPNegocioException")})
    @RequestWrapper(localName = "registrarAvisoSinDetencion", targetNamespace = "http://ws.service.nsjp.segob.gob.mx/", className = "mx.gob.segob.nsjp.ws.cliente.avisodetencion.RegistrarAvisoSinDetencion")
    @WebMethod
    @ResponseWrapper(localName = "registrarAvisoSinDetencionResponse", targetNamespace = "http://ws.service.nsjp.segob.gob.mx/", className = "mx.gob.segob.nsjp.ws.cliente.avisodetencion.RegistrarAvisoSinDetencionResponse")
    public mx.gob.segob.nsjp.ws.cliente.avisodetencion.AvisoDesignacionWSDTO registrarAvisoSinDetencion(
            @WebParam(name = "arg0", targetNamespace = "")
            mx.gob.segob.nsjp.ws.cliente.avisodetencion.AvisoDesignacionWSDTO arg0,
            @WebParam(name = "arg1", targetNamespace = "")
            java.lang.Long arg1,
            @WebParam(name = "arg2", targetNamespace = "")
            java.lang.String arg2,
            @WebParam(name = "arg3", targetNamespace = "")
            java.lang.Long arg3
        ) throws NSJPNegocioException_Exception;
    
}
