package mx.gob.segob.nsjp.ws.cliente.avisodetencion;

import java.net.MalformedURLException;
import java.net.URL;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;

/**
 * This class was generated by Apache CXF 2.4.2
 * 2012-01-16T19:57:36.172-06:00
 * Generated source version: 2.4.2
 * 
 */
@WebServiceClient(name = "RegistrarAvisoSinDetencionDeAreaExternaExporterImplService", 
                  wsdlLocation = "http://localhost:8080/nsjp-web/RegistrarAvisoSinDetencionDeAreaExternaExporterImplService?wsdl",
                  targetNamespace = "http://impl.ws.service.nsjp.segob.gob.mx/") 
public class RegistrarAvisoSinDetencionDeAreaExternaExporterImplService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://impl.ws.service.nsjp.segob.gob.mx/", "RegistrarAvisoSinDetencionDeAreaExternaExporterImplService");
    public final static QName RegistrarAvisoSinDetencionDeAreaExternaExporterImplPort = new QName("http://impl.ws.service.nsjp.segob.gob.mx/", "RegistrarAvisoSinDetencionDeAreaExternaExporterImplPort");
    static {
        URL url = null;
        try {
            url = new URL("http://localhost:8080/nsjp-web/RegistrarAvisoSinDetencionDeAreaExternaExporterImplService?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(RegistrarAvisoSinDetencionDeAreaExternaExporterImplService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://localhost:8080/nsjp-web/RegistrarAvisoSinDetencionDeAreaExternaExporterImplService?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public RegistrarAvisoSinDetencionDeAreaExternaExporterImplService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public RegistrarAvisoSinDetencionDeAreaExternaExporterImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public RegistrarAvisoSinDetencionDeAreaExternaExporterImplService() {
        super(WSDL_LOCATION, SERVICE);
    }
    

    /**
     *
     * @return
     *     returns RegistrarAvisoSinDetencionDeAreaExternaExporter
     */
    @WebEndpoint(name = "RegistrarAvisoSinDetencionDeAreaExternaExporterImplPort")
    public RegistrarAvisoSinDetencionDeAreaExternaExporter getRegistrarAvisoSinDetencionDeAreaExternaExporterImplPort() {
        return super.getPort(RegistrarAvisoSinDetencionDeAreaExternaExporterImplPort, RegistrarAvisoSinDetencionDeAreaExternaExporter.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns RegistrarAvisoSinDetencionDeAreaExternaExporter
     */
    @WebEndpoint(name = "RegistrarAvisoSinDetencionDeAreaExternaExporterImplPort")
    public RegistrarAvisoSinDetencionDeAreaExternaExporter getRegistrarAvisoSinDetencionDeAreaExternaExporterImplPort(WebServiceFeature... features) {
        return super.getPort(RegistrarAvisoSinDetencionDeAreaExternaExporterImplPort, RegistrarAvisoSinDetencionDeAreaExternaExporter.class, features);
    }

}
